name = "GreenBoogers"
author = "TS2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1b73adf5dfc7cd045d4a6f78e39d737c29a92c508c5a76ca076b8ea37baa36b"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
