name = "GreenBoogers"
author = "TS2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd03520a0ca26d0e1fcdcb61c6b999c0d992bea93726e58742cb07848dd6485c"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
